# Generated by Django 4.2.7 on 2025-09-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="categoryId",
        ),
    ]
