# Generated by Django 4.2.7 on 2025-09-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_category_product_categoryid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categoryId",
            new_name="category",
        ),
    ]
